import { afterEach, describe, expect, it, vi } from 'vitest'
import { downmix, encodeMonoPcm16Wav, RecordingError, RecordingSession } from './audioRecording'

afterEach(() => vi.restoreAllMocks())

describe('browser WAV encoding', () => {
  it('downmixes channels using their arithmetic mean', () => { expect(Array.from(downmix([new Float32Array([1, -1]), new Float32Array([-1, 1])]))).toEqual([0, 0]) })
  it('encodes a mono PCM-16 RIFF/WAVE file with consistent metadata', async () => { const blob = encodeMonoPcm16Wav(new Float32Array([0, .5, -.5]), 16000); const view = new DataView(await blob.arrayBuffer()); const text = (offset: number) => String.fromCharCode(...new Uint8Array(view.buffer.slice(offset, offset + 4))); expect(text(0)).toBe('RIFF'); expect(text(8)).toBe('WAVE'); expect(view.getUint16(20, true)).toBe(1); expect(view.getUint16(22, true)).toBe(1); expect(view.getUint32(24, true)).toBe(16000); expect(view.getUint16(34, true)).toBe(16); expect(view.getUint32(40, true)).toBe(6); expect(blob.type).toBe('audio/wav') })
  it('rejects a recording shorter than the minimum duration', async () => { const session = new RecordingSession() as unknown as { stopped: boolean; chunks: Float32Array[]; sampleRate: number; stop: () => Promise<File> }; session.stopped = false; session.chunks = [new Float32Array(15999)]; session.sampleRate = 16000; await expect(session.stop()).rejects.toBeInstanceOf(RecordingError) })
  it('stops tracks, disconnects nodes, closes the context, and builds a WAV after stopping', async () => { const stop = vi.fn(); const disconnect = vi.fn(); const close = vi.fn().mockResolvedValue(undefined); const session = new RecordingSession() as unknown as { stopped: boolean; chunks: Float32Array[]; sampleRate: number; stream: { getTracks: () => { stop: () => void }[] }; node: { disconnect: () => void }; source: { disconnect: () => void }; context: { state: string; close: () => Promise<void> }; stop: () => Promise<File> }; session.stopped = false; session.chunks = [new Float32Array(16000)]; session.sampleRate = 16000; session.stream = { getTracks: () => [{ stop }] }; session.node = { disconnect }; session.source = { disconnect }; session.context = { state: 'running', close }; const file = await session.stop(); expect(file.type).toBe('audio/wav'); expect(stop).toHaveBeenCalled(); expect(disconnect).toHaveBeenCalledTimes(2); expect(close).toHaveBeenCalled() })
  it('reports microphone permission denial without retaining a session', async () => { const previous = navigator.mediaDevices; const previousContext = window.AudioContext; const previousNode = window.AudioWorkletNode; Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: { getUserMedia: vi.fn().mockRejectedValue(new DOMException('', 'NotAllowedError')) } }); Object.defineProperty(window, 'AudioContext', { configurable: true, value: class {} }); Object.defineProperty(window, 'AudioWorkletNode', { configurable: true, value: class {} }); await expect(new RecordingSession().start(() => undefined)).rejects.toThrow(/permission was denied/i); Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: previous }); Object.defineProperty(window, 'AudioContext', { configurable: true, value: previousContext }); Object.defineProperty(window, 'AudioWorkletNode', { configurable: true, value: previousNode }) })
})
